# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# Command to start on workspace startup
tasks:
  - init: npm install
    command: npm run dev
  - openMode: tab-after
    command: echo for git
